[Icon Theme]
Name=Vanilla3
Comment=The Vanilla 3 icon pack by @Elttob_
Inherits=Roblox

[ui/16x/100]
Size=15
scale=1
[ui/16x/150]
Size=15
scale=1.5
[ui/16x/200]
Size=15
scale=2

[general/16x/100]
Size=15
scale=1
[general/16x/150]
Size=15
scale=1.5
[general/16x/200]
Size=15
scale=2
[general/32x/100]
Size=31
scale=1
[general/32x/150]
Size=31
scale=1.5
[general/32x/200]
Size=31
scale=2

[instance/16x/100]
Size=15
scale=1
[instance/16x/150]
Size=15
scale=1.5
[instance/16x/200]
Size=15
scale=2